name: CI
on:
  workflow_dispatch:
    inputs:
      run_build:
        description: "Build on request"
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'
  pull_request:
  push:
    tags:
      - 'v*'
    branches:
      - main
      - dev

jobs:
  dev:
    if |
      (github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))) 
      || (github.event_name == 'workflow_dispatch' && github.event.inputs.run_build == 'true')
  steps: 
    - name: Debug tag output
      run: |
        echo "test secret: ${{ secrets.TEST_SECRET }}"